name: Build Cheat Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone & Build Cheat Engine
        run: |
          git clone https://github.com/Twig6943/cheat-engine.git
          cd "cheat-engine\Cheat Engine"
          pwd
          dir D:\a\cheat-engine\cheat-engine

    steps:
      - uses: actions/checkout@v4
      - uses: gcarreno/setup-lazarus@v3
        with:
      lazarus-version: "1.6.4"
      include-packages: "Synapse 40.1"
      with-cache: true
      - run: lazbuild cheatengine.lpi
      #- run: Cheat Engine
     


      - name: Upload Cheat Engine Executable
        uses: actions/upload-artifact@v4
        with:
          name: cheatengine
          path: cheat-engine\Cheat Engine\cheatengine.exe
