name: Build Cheat Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Lazarus 1.6.4 Installer
        run: |
          Invoke-WebRequest -Uri "https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-win64.exe" -OutFile "lazarus.exe"

      - name: Install Lazarus 1.6.4 Silently
        run: |
          .\lazarus.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /DIR="C:\lazarus"

      - name: Add Lazarus to PATH
        run: |
          echo "C:\lazarus" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Create Lazarus Config Directory
        run: |
          mkdir C:\laz_config
          Start-Process -FilePath "C:\lazarus\lazarus.exe" -ArgumentList "--primary-config-path=C:\laz_config" -Wait

      - name: Clone & Build Cheat Engine
        run: |
          git clone https://github.com/Twig6943/cheat-engine.git
          cd "cheat-engine\Cheat Engine"
          lazbuild --primary-config-path=C:\laz_config cheatengine.lpi
