jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Lazarus 1.6.4 Installer
        run: |
          Invoke-WebRequest -Uri "https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-win64.exe" -OutFile "lazarus.exe"

      - name: Install Lazarus 1.6.4 Silently
        run: |
          .\lazarus.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-

      - name: Set LAZARUS_DIR
        run: |
          echo "LAZARUS_DIR=C:\lazarus" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Add Lazarus to PATH
        run: |
          echo "C:\lazarus" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Clone & Build Cheat Engine
        run: |
          git clone https://github.com/Twig6943/cheat-engine.git
          cd "cheat-engine\Cheat Engine"
          lazbuild cheatengine.lpi
