name: Build Cheat Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Cheat Engine Repository
        run: |
          git clone https://github.com/Twig6943/cheat-engine.git

      - name: Download Lazarus Installer
        run: |
          curl -L -o lazarus.exe https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-win64.exe

      - name: Install Lazarus Silently
        run: |
          .\lazarus.exe /VERYSILENT /DIR="C:\Lazarus" /COMPONENTS="main"

      - name: Add Lazarus to PATH
        shell: pwsh
        run: |
          echo "C:\Lazarus" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Create Lazarus Environment Config
        shell: pwsh
        run: |
          $configDir = "$env:USERPROFILE\AppData\Local\lazarus"
          New-Item -ItemType Directory -Force -Path $configDir | Out-Null
          $envXml = @"
          <CONFIG>
            <EnvironmentOptions>
              <LazarusDirectory Value="C:\Lazarus"/>
              <CompilerPath Value="C:\Lazarus\fpc\3.0.2\bin\x86_64-win64\fpc.exe"/>
            </EnvironmentOptions>
          </CONFIG>
          "@
          $envXml | Out-File -Encoding utf8 "$configDir\environmentoptions.xml"

      - name: Add Required Packages
        shell: pwsh
        run: |
          Copy-Item -Recurse -Force "cheat-engine\packages\synapse" "C:\Lazarus\components\synapse"
          & "C:\Lazarus\lazbuild.exe" --add-package "C:\Lazarus\components\synapse\synapse.lpk"

      - name: Build Cheat Engine
        run: |
          cd "cheat-engine\Cheat Engine"
          "C:\Lazarus\lazbuild.exe" cheatengine.lpi

      - name: Upload Cheat Engine Executable
        uses: actions/upload-artifact@v4
        with:
          name: cheatengine
          path: cheat-engine/Cheat Engine/bin
