name: Install Lazarus Custom

on:
  workflow_dispatch:

jobs:
  install-lazarus:
    runs-on: windows-latest

    steps:
      - name: Checkout (placeholder)
        uses: actions/checkout@v4

      - name: Download Lazarus Installer
        run: |
          curl -L -o lazarus.exe https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-win64.exe

      - name: Install Lazarus Silently
        run: |
          .\lazarus.exe /VERYSILENT /DIR="C:\lazarus" /COMPONENTS="main"

      - name: Add Lazarus to PATH
        shell: pwsh
        run: |
          echo "C:\lazarus" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Create Lazarus Environment Config
        shell: pwsh
        run: |
          $configDir = "$env:USERPROFILE\AppData\Local\lazarus"
          New-Item -ItemType Directory -Force -Path $configDir | Out-Null
          $envXml = @"
          <CONFIG>
            <EnvironmentOptions>
              <LazarusDirectory Value='C:\lazarus'/>
              <CompilerPath Value='C:\lazarus\fpc\3.0.2\bin\x86_64-win64\fpc.exe'/>
            </EnvironmentOptions>
          </CONFIG>
          "@
          $envXml | Out-File -Encoding utf8 "$configDir\environmentoptions.xml"

      - name: Install Synapse Package
        shell: pwsh
        run: |
          # Example: Assuming you commit Synapse to the repo under packages/synapse/
          Copy-Item -Recurse -Force "packages\synapse" "C:\lazarus\components\synapse"
          & "C:\lazarus\lazbuild.exe" --add-package "C:\lazarus\components\synapse\synapse.lpk"
