name: Build Cheat Engine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Lazarus + FPC Source
        run: |
          Invoke-WebRequest -Uri "https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-win64.exe" -OutFile "lazarus.exe"
          Invoke-WebRequest -Uri "https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-cross-i386-win32-win64.exe" -OutFile "lazarus-ext.exe"

      - name: Install Lazarus
        run: |
          .\lazarus.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /DIR="C:\lazarus"
          .\lazarus-ext.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /DIR="C:\lazarus"

      - name: Add Lazarus to PATH
        run: |
          echo "C:\lazarus" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Set Lazarus Environment Variables
        run: |
          echo "FPCTARGET=x86_64-win64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "FPCTARGETCPU=x86_64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Where Lazarus
        run: |
          where lazarus

      - name: Clone & Build Cheat Engine
        run: |
          git clone https://github.com/Twig6943/cheat-engine.git
          cd "cheat-engine\Cheat Engine"
          dir C:\lazarus
          lazbuild --lazarusdir=C:\lazarus cheatengine.lpi

      - name: Upload Cheat Engine Executable
        uses: actions/upload-artifact@v4
        with:
          name: cheatengine
          path: cheat-engine\Cheat Engine\cheatengine.exe
