name: Setup Lazarus Manually

on:
  workflow_dispatch:

jobs:
  setup-lazarus:
    runs-on: windows-latest

    steps:
      - name: Create Install Directory
        run: |
          mkdir D:\a\_temp\installers

      - name: Download Lazarus 1.6.4
        run: |
          curl -L -o D:\a\_temp\installers\lazarus-1.6.4.exe https://github.com/Twig6943/cheat-engine/releases/download/1.0/lazarus-1.6.4-fpc-3.0.2-win64.exe

      - name: Install Lazarus Silently
        run: |
          D:\a\_temp\installers\lazarus-1.6.4.exe /VERYSILENT /SP- /DIR=D:\a\_temp\installers\lazarus

      - name: Add Lazarus to PATH
        shell: pwsh
        run: |
          echo "D:\a\_temp\installers\lazarus" | Out-File -Append $env:GITHUB_PATH
          echo "D:\a\_temp\installers\lazarus\fpc\3.0.2\bin\x86_64-win64" | Out-File -Append $env:GITHUB_PATH

      - name: Download Synapse Package
        run: |
          curl -L -o D:\a\_temp\Synapse40.1.zip ^
            "https://packages.lazarus-ide.org/Synapse40.1.zip"

      - name: Extract Synapse Package
        shell: pwsh
        run: |
          $zipPath = "D:\a\_temp\Synapse40.1.zip"
          $extractPath = "D:\a\_temp\synapse40.1"
          Expand-Archive -LiteralPath $zipPath -DestinationPath $extractPath -Force

      - name: Compile Synapse Package
        run: |
          D:\a\_temp\installers\lazarus\lazbuild.exe ^
            D:\a\_temp\synapse40.1\synapse40.1\laz_synapse.lpk
